import { useEffect, useState } from "react";
import { PortalLayout } from "@/components/layout/PortalLayout";
import { PageHeader } from "@/components/portal/PageHeader";
import { StatCard } from "@/components/portal/StatCard";
import { StatusBadge } from "@/components/portal/StatusBadge";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useSession } from "@/hooks/useSession";
import { supabase } from "@/integrations/supabase/client";
import { Wallet, Receipt, Download, IndianRupee, TrendingUp } from "lucide-react";
import { toast } from "sonner";

export default function Payments() {
  const { user, loading } = useSession();
  const [pays, setPays] = useState<any[]>([]);
  const [downloadedReceipt, setDownloadedReceipt] = useState<any | null>(null);
  const [selectedReceipt, setSelectedReceipt] = useState<any | null>(null);
  const [receiptDialogOpen, setReceiptDialogOpen] = useState(false);

  useEffect(() => {
    if (!user) return;
    supabase.from("payments").select("*,applications(reference_no,services(name))").eq("citizen_id", user.id).order("created_at", { ascending: false }).then(({ data }) => setPays((data as any) || []));
  }, [user]);

  const total = pays.filter((p) => p.status === "success").reduce((s, p) => s + Number(p.amount), 0);
  const refunds = pays.filter((p) => p.status === "refunded").reduce((s, p) => s + Number(p.amount), 0);

  const getReceiptStatusLabel = (status: string) => {
    if (status === "success") return "Transaction successful";
    if (status === "refunded") return "Refunded";
    return status.charAt(0).toUpperCase() + status.slice(1);
  };

  const createReceiptHtml = (payment: any) => {
    const serviceName = payment.applications?.services?.name || "Service";
    const date = new Date(payment.created_at).toLocaleString("en-IN");
    const statusLabel = getReceiptStatusLabel(payment.status);
    const amount = `₹${Number(payment.amount).toLocaleString("en-IN")}`;
    const userEmail = user?.email || "Unknown";

    return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Receipt - ${payment.txn_id}</title>
  <style>
    body { margin: 0; padding: 0; font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #f8fafc; color: #0f172a; }
    .receipt { max-width: 760px; margin: 32px auto; padding: 32px; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 24px; }
    .header { display: flex; justify-content: space-between; gap: 16px; align-items: flex-start; }
    .header h1 { margin: 0; font-size: 1.75rem; letter-spacing: -0.03em; }
    .status { display: inline-flex; gap: 0.5rem; align-items: center; padding: 0.75rem 1rem; border-radius: 9999px; background: #ecfdf5; color: #047857; font-weight: 700; font-size: 0.85rem; }
    .section { margin-top: 24px; display: grid; gap: 16px; grid-template-columns: repeat(2, minmax(0, 1fr)); }
    .card { padding: 20px; border-radius: 20px; background: #f8fafc; border: 1px solid #e2e8f0; }
    .label { margin: 0 0 8px; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.12em; color: #64748b; }
    .value { margin: 0; font-size: 1rem; font-weight: 700; color: #0f172a; word-break: break-all; }
    .footer { margin-top: 32px; padding-top: 24px; border-top: 1px solid #e2e8f0; color: #475569; font-size: 0.95rem; line-height: 1.6; }
  </style>
</head>
<body>
  <div class="receipt">
    <div class="header">
      <div>
        <h1>Bharat Sewa Receipt</h1>
        <p style="margin: 12px 0 0; color: #475569;">Payment confirmed for your government service application.</p>
      </div>
      <div class="status">${statusLabel}</div>
    </div>

    <div class="section">
      <div class="card"><p class="label">Transaction ID</p><p class="value">${payment.txn_id}</p></div>
      <div class="card"><p class="label">Amount paid</p><p class="value">${amount}</p></div>
      <div class="card"><p class="label">Service</p><p class="value">${serviceName}</p></div>
      <div class="card"><p class="label">Payment method</p><p class="value">${payment.method}</p></div>
      <div class="card"><p class="label">Date</p><p class="value">${date}</p></div>
      <div class="card"><p class="label">Citizen</p><p class="value">${userEmail}</p></div>
    </div>

    <div class="footer">
      Receipt generated by Bharat Sewa. Please keep this receipt for your records and for future reference.
    </div>
  </div>
</body>
</html>`;
  };

  const downloadReceipt = (payment: any) => {
    const html = createReceiptHtml(payment);
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `receipt-${payment.txn_id}.html`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success(`Receipt downloaded: ${payment.txn_id}`);
    setDownloadedReceipt(payment);
  };

  if (loading) return <PortalLayout role="citizen"><PageHeader title="Loading..." subtitle="" /></PortalLayout>;
  if (!user) return null;

  return (
    <PortalLayout role="citizen">
      <PageHeader title="Payments & Receipts" subtitle="View transactions and pay government fees online." />

      <Dialog open={receiptDialogOpen} onOpenChange={(open) => {
        if (!open) {
          setSelectedReceipt(null);
        }
        setReceiptDialogOpen(open);
      }}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Receipt preview</DialogTitle>
            <DialogDescription>Review your receipt before downloading a styled copy.</DialogDescription>
          </DialogHeader>

          {selectedReceipt ? (
            <div className="space-y-6">
              <div className="rounded-3xl border border-border bg-muted p-5">
                <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                  <div>
                    <p className="text-sm uppercase tracking-[0.24em] text-muted-foreground">Bharat Sewa Receipt</p>
                    <p className="mt-2 text-xl font-semibold">{getReceiptStatusLabel(selectedReceipt.status)}</p>
                  </div>
                  <StatusBadge status={selectedReceipt.status} />
                </div>
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <div className="rounded-3xl border border-border bg-background p-4">
                  <p className="text-sm text-muted-foreground">Transaction ID</p>
                  <p className="mt-2 font-semibold break-all">{selectedReceipt.txn_id}</p>
                </div>
                <div className="rounded-3xl border border-border bg-background p-4">
                  <p className="text-sm text-muted-foreground">Amount paid</p>
                  <p className="mt-2 text-xl font-semibold">₹{Number(selectedReceipt.amount).toLocaleString("en-IN")}</p>
                </div>
                <div className="rounded-3xl border border-border bg-background p-4">
                  <p className="text-sm text-muted-foreground">Service</p>
                  <p className="mt-2 font-semibold">{selectedReceipt.applications?.services?.name || "—"}</p>
                </div>
                <div className="rounded-3xl border border-border bg-background p-4">
                  <p className="text-sm text-muted-foreground">Payment method</p>
                  <p className="mt-2 font-semibold">{selectedReceipt.method}</p>
                </div>
                <div className="rounded-3xl border border-border bg-background p-4">
                  <p className="text-sm text-muted-foreground">Date</p>
                  <p className="mt-2 font-semibold">{new Date(selectedReceipt.created_at).toLocaleString("en-IN")}</p>
                </div>
                <div className="rounded-3xl border border-border bg-background p-4">
                  <p className="text-sm text-muted-foreground">Citizen</p>
                  <p className="mt-2 font-semibold">{user?.email || "Unknown"}</p>
                </div>
              </div>
            </div>
          ) : (
            <div className="py-8 text-center text-sm text-muted-foreground">Select a transaction from the table to preview a receipt.</div>
          )}

          <DialogFooter>
            <Button variant="secondary" disabled={!selectedReceipt} onClick={() => selectedReceipt && downloadReceipt(selectedReceipt)}>
              Download receipt
            </Button>
            <Button variant="ghost" onClick={() => setReceiptDialogOpen(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {downloadedReceipt ? (
        <Card className="mb-6 border-emerald-200 bg-emerald-50 text-emerald-950 shadow-sm">
          <div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-start gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-700">
                <Receipt className="h-5 w-5" />
              </div>
              <div>
                <p className="font-semibold text-emerald-900">Receipt downloaded successfully</p>
                <p className="mt-1 text-sm text-slate-700">Your receipt for transaction <span className="font-medium">{downloadedReceipt.txn_id}</span> is ready in your downloads folder.</p>
              </div>
            </div>
            <div className="flex flex-col gap-2 sm:flex-row">
              <Button size="sm" variant="secondary" onClick={() => downloadReceipt(downloadedReceipt)}>
                <Download className="h-4 w-4" />
                Download again
              </Button>
              <Button size="sm" variant="ghost" onClick={() => setDownloadedReceipt(null)}>
                Dismiss
              </Button>
            </div>
          </div>
        </Card>
      ) : null}

      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <StatCard label="Total Paid" value={`₹${total.toLocaleString("en-IN")}`} icon={Wallet} tone="success" />
        <StatCard label="Transactions" value={String(pays.length)} icon={Receipt} tone="primary" />
        <StatCard label="Pending Dues" value="₹0" icon={IndianRupee} tone="warning" />
        <StatCard label="Refunds" value={`₹${refunds.toLocaleString("en-IN")}`} icon={TrendingUp} tone="accent" />
      </div>

      <Card className="p-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-display font-semibold text-lg">Transaction History</h3>
          <Badge variant="outline">All time</Badge>
        </div>
        {pays.length === 0 ? (
          <p className="text-sm text-muted-foreground text-center py-12">No payments yet. Payments are made automatically when you apply for a service.</p>
        ) : (
          <div className="overflow-x-auto -mx-6 px-6">
            <table className="w-full text-sm min-w-[700px]">
              <thead>
                <tr className="text-left text-xs uppercase tracking-wider text-muted-foreground border-b border-border">
                  <th className="py-3 font-semibold">Transaction ID</th>
                  <th className="py-3 font-semibold">Service</th>
                  <th className="py-3 font-semibold">Date</th>
                  <th className="py-3 font-semibold">Method</th>
                  <th className="py-3 font-semibold">Status</th>
                  <th className="py-3 font-semibold text-right">Amount</th>
                  <th className="py-3 font-semibold text-right">Receipt</th>
                </tr>
              </thead>
              <tbody>
                {pays.map((p) => (
                  <tr key={p.id} className="border-b border-border last:border-0 hover:bg-secondary/40">
                    <td className="py-3 font-mono text-xs whitespace-nowrap">{p.txn_id}</td>
                    <td className="py-3 font-medium">{p.applications?.services?.name || "—"}</td>
                    <td className="py-3 text-muted-foreground whitespace-nowrap">{new Date(p.created_at).toLocaleDateString("en-IN")}</td>
                    <td className="py-3 text-muted-foreground">{p.method}</td>
                    <td className="py-3"><StatusBadge status={p.status} /></td>
                    <td className="py-3 text-right font-semibold">₹{Number(p.amount).toLocaleString("en-IN")}</td>
                    <td className="py-3 text-right">
                      <Button size="sm" variant="secondary" className="h-9 px-3" onClick={() => {
                        setSelectedReceipt(p);
                        setReceiptDialogOpen(true);
                      }}>
                        <Receipt className="h-4 w-4" />
                        View
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </PortalLayout>
  );
}
